### PR TITLE
Fixed angle computation

### PR DESCRIPTION
**Pull request by kolesnikov-pasha**
Just a wrong degree to radian formula

### CODE REVIEW

**Comment by izzytwosheds** [comment]
Did this code actually run?

**Comment by kolesnikov-pasha** [comment]
> Did this code actually run?

It shouldn't as I understand, but it might if user is using some not accurate math equations to compute angle. For example, it might be called if previously user computed angle from radians to degrees.

**Comment by kolesnikov-pasha** [comment]
Or if user just want to rotate video in a strange way:)

**Comment by izzytwosheds** [comment]
That angle is supposed to be video orientation (portrait, landscape, etc.), which is expected to be multiples of 90 degrees. But I guess one can expect any kind of user input. :)

**Pull request merged**
